### ISSUE TITLE
Ascii codec problem, can't use laradock

### ISSUE THREAD

**Issue by janva255** [laradock/laradock#1005]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 26ee54a4ad2b8723de3067dbaa199d34ca45cb68
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10 x64

##### What seems to be going wrong?
I try to run the basic steps to get everything up  [http://laradock.io/introduction/](from here) and it's not working when i run docker-compose up -d nginx mysql redis beanstalkd or docker-compose up -d nginx mysql

It throws this:
```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 113, in perform_command
  File "compose\cli\command.py", line 36, in project_from_options
  File "compose\cli\command.py", line 103, in get_project
  File "compose\config\config.py", line 333, in load
  File "compose\config\config.py", line 457, in load_services
  File "compose\config\config.py", line 436, in build_services
  File "compose\config\config.py", line 421, in build_service
  File "compose\config\config.py", line 668, in process_service
  File "compose\config\config.py", line 988, in resolve_volume_paths
  File "compose\config\config.py", line 998, in resolve_volume_path
  File "ntpath.py", line 311, in expanduser
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 14: ordinal not in range(128)
Failed to execute script docker-compose
```
_____

##### What should be happening instead?

_____

##### How might we be able to reproduce the error?

_____

### Relevant Code:

```
// place code here
```

**Comment by pawlox** [comment]
I have the same problem. What is your Windows user name? Mine contains non ascii characters and I think this is the problem (the same was with Vagrant). Some users recommend to install docker in Python 3 environment instead 2.7 but I have installed Python 3 and it didn't helped :/
