### ISSUE TITLE
Error on nginx build

### ISSUE THREAD

**Issue by GinoPane** [laradock/laradock#1404]
### Info:
- Docker version (`$ docker --version`): Docker version 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): 0077de28a13feea669f9d46ef21c20477fa6dbb0
- System info (Mac, PC, Linux): Windows 10 Enterprise
- System info disto/version: 1709 (16299.248)

### Issue:
I'm constantly getting this error when building `nginx` image by running `docker-compose build nginx`:

```
Step 11/11 : EXPOSE 80 443
 ---> Running in 743541d147cd
Removing intermediate container 743541d147cd
 Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 254, in build
  File "compose\project.py", line 364, in build
  File "compose\service.py", line 972, in build
  File "compose\progress_stream.py", line 23, in stream_output
  File "compose\progress_stream.py", line 90, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
```

It can fail at the beginning (step 2 or something like that). After retry it goes further. 

And I always get this error when trying to build `workspace`:

```
Building workspace
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_AEROSPIKE} = true ]; then     apt-get update -yqq &&     apt-get -y install sudo wget &&     curl -L -o /tmp/aerospike-client-php.tar.gz "https://github.com/aerospike/aerospike-cli
ent-php/archive/master.tar.gz"     && mkdir -p aerospike-client-php     && tar -C aerospike-client-php -zxvf /tmp/aerospike-client-php.tar.gz --strip 1     && (         cd aerospike-client-php/src
  && phpize         && ./build.sh         && make install     )     && rm /tmp/aerospike-client-php.tar.gz ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_LINUXBREW} = true ]; then     apt-get upgrade -y &&     apt-get install -y build-essential make cmake scons curl git       ruby autoconf automake autoconf-archive       gettext lib
tool flex bison       libbz2-dev libcurl4-openssl-dev       libexpat-dev libncurses-dev &&     git clone --depth=1 https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew &&     echo "" >> ~/.bashrc &&
  echo 'export PKG_CONFIG_PATH"=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:$
PKG_CONFIG_PATH"' >> ~/.bashrc &&     echo 'export LINUXBREWHOME="$HOME/.linuxbrew"' >> ~/.bashrc &&     echo 'export PATH="$LINUXBREWHOME/bin:$PATH"' >> ~/.bashrc &&     echo 'export MANPATH="$LINUXBREW
HOME/man:$MANPATH"' >> ~/.bashrc &&     echo 'export PKG_CONFIG_PATH="$LINUXBREWHOME/lib64/pkgconfig:$LINUXBREWHOME/lib/pkgconfig:$PKG_CONFIG_PATH"' >> ~/.bashrc &&     echo 'export LD_LIBRARY_PATH="$LIN
UXBREWHOME/lib64:$LINUXBREWHOME/lib:$LD_LIBRARY_PATH"' >> ~/.bashrc ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_MSSQL} = true ]; then         cd / &&         apt-get update -yqq &&         apt-get install -y --force-yes wget apt-transport-https curl freetds-common libsybdb5 freetds-bin unixo
dbc unixodbc-dev &&         cd / &&         echo "deb http://packages.dotdeb.org jessie all"         | tee /etc/apt/sources.list.d/dotdeb.list         && wget -qO- https://www.dotdeb.org/dotdeb.gpg
   | apt-key add -         && apt-get update -yqq         && apt-get upgrade -qq &&         cd / &&         apt-get update -yqq &&         apt-get install -y whiptail         unixodbc libgss3 odbcinst de
vscripts debhelper dh-exec dh-autoreconf libreadline-dev libltdl-dev         && dget -u -x http://http.debian.net/debian/pool/main/u/unixodbc/unixodbc_2.3.1-3.dsc         && cd unixodbc-*/         && ./c
onfigure && make && make install         && cp -v ./exe/odbc_config /usr/local/bin/ &&         printf '#!/bin/bash\nif [ "$*" == "-p" ]; then echo "x86_64"; else /bin/uname "$@"; fi'         | tee /usr/l
ocal/bin/uname         && chmod +x /usr/local/bin/uname &&         cd / &&         wget -nv -O msodbcsql-13.0.0.0.tar.gz         "https://meetsstorenew.blob.core.windows.net/contianerhd/Ubuntu%20Tar/msod
bcsql-13.0.0.0.tar.gz?st=2016-10-18T17%!A(MISSING)29%!A(MISSING)00Z&se=2022-10-19T17%!A(MISSING)29%!A(MISSING)00Z&sp=rl&sv=2015-04-05&sr=b&sig=cDwPfrouVeIQf0vi%!B(MISSING)nKt%!B(MISSING)zX8Z8caIYvRCmicDL
5oknY%!D(MISSING)"         && tar -xf msodbcsql-13.0.0.0.tar.gz         && cd msodbcsql-*/         && ldd lib64/libmsodbcsql-13.0.so.0.0         && ./install.sh install --accept-license         && ls -l
/opt/microsoft/msodbcsql/         && odbcinst -q -d -n "ODBC Driver 13 for SQL Server" &&     pecl install sqlsrv-4.0.8 &&     pecl install pdo_sqlsrv-4.0.8 &&     apt-get install -y locales     && echo
"en_US.UTF-8 UTF-8" > /etc/locale.gen     && locale-gen     && echo "extension=sqlsrv.so" > /etc/php/7.1/cli/conf.d/20-sqlsrv.ini     && echo "extension=pdo_sqlsrv.so" > /etc/php/7.1/cli/conf.d/20-pdo_sq
lsrv.ini ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_SYMFONY} = true ]; then   mkdir -p /usr/local/bin   && curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony   && chmod a+x /usr/local/bin/symfony   && echo 'alias dev=
"php bin/console -e=dev"' >> ~/.bashrc   && echo 'alias prod="php bin/console -e=prod"' >> ~/.bashrc ;fi
[WARNING]: Empty continuation lines will become errors in a future release.
Step 1/158 : FROM laradock/workspace:2.0-71
2.0-71: Pulling from laradock/workspace
22ecafbbcc4a: Pulling fs layer
580435e0a086: Download complete
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 254, in build
  File "compose\project.py", line 364, in build
  File "compose\service.py", line 972, in build
  File "compose\progress_stream.py", line 44, in stream_output
  File "compose\progress_stream.py", line 63, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
```

### Expected behavior:
No errors on build.

**Comment by GinoPane** [comment]
It looks like the problem is described here: https://github.com/docker/compose/issues/5019.

Nothing wrong with Laradock.

Running script from ConEmu seems to work.
