### ISSUE TITLE
Error message : Mongodb is not loaded but it is not used

### ISSUE THREAD

**Issue by Selsynn** [LaraDock/laradock#177]
I'm beginner with laravel and i didn't do php for a long time and I'm bit confuse

I mount the docker component that i want and i have this log 
(I merely want a laravel project with a postgres database)
--> docker-compose up workspace postgres php-fpm
```
Recreating laradock_volumes_data_1
Starting laradock_volumes_source_1
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
Recreating laradock_postgres_1
Attaching to laradock_workspace_1, laradock_php-fpm_1, laradock_postgres_1
postgres_1            | LOG:  database system was shut down at 2016-07-25 15:41:41 UTC
postgres_1            | LOG:  MultiXact member wraparound protections are now enabled
postgres_1            | LOG:  database system is ready to accept connections
postgres_1            | LOG:  autovacuum launcher started
workspace_1           | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
workspace_1           | *** Running /etc/rc.local...
workspace_1           | *** Booting runit daemon...
workspace_1           | *** Runit started as PID 7
workspace_1           | Jul 25 15:33:37 18c7fe91f8a2 syslog-ng[12]: syslog-ng starting up; version='3.5.6'
workspace_1           | Jul 25 15:39:01 18c7fe91f8a2 CRON[20]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && /usr/lib/php/sessionclean)
php-fpm_1             | [25-Jul-2016 15:33:37] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mongodb.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mongodb.so: cannot open shared object file: No such file or directory in Unknown on line 0
php-fpm_1             | [25-Jul-2016 15:33:37] NOTICE: fpm is running, pid 1
php-fpm_1             | [25-Jul-2016 15:33:37] NOTICE: ready to handle connections
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 58, in main
  File "compose/cli/main.py", line 109, in perform_command
  File "compose/cli/main.py", line 747, in up
  File "compose/cli/log_printer.py", line 86, in run
  File "compose/cli/log_printer.py", line 222, in consume_queue
ssl.SSLError: ('The read operation timed out',)
docker-compose returned -1
```

Is it okay ? Because in the same time, i can't open the link in the browser. (I'm at lost at what is not ok, without the error message about mangodb)
I deleted all mentions to mangodb in the docker-compose.yml, but do I need to do another thing ?
What is the problems ? (I think it is possible to not used Mangodb ?)

**Comment by Kauhat** [comment]
Hi @Selsynn 

Can you try running `docker-compose up -d nginx postgres workspace` (note the extra `-d`!) as this will launch containers in the background and may help.

**Comment by Selsynn** [comment]
Is it mandatory to use nginx ? 

And... it works, thank you very much !

**Comment by Kauhat** [comment]
Nope, you can use just `php-fpm` if you want to, it's just launched automatically alongside nginx!

**Comment by Selsynn** [comment]
Thank you.
