### ISSUE TITLE
Can't run gitlab on local pc

### ISSUE THREAD

**Issue by sanpakyou027** [laradock/laradock#1849]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 9cfe5c61565a77b4da40817f3e1d45e18ef5920d
- System info (Mac, PC, Linux):  PC
- System info disto/version: windows 10 pro version 1803  build 17134 

### Issue:
I'm having a problem to run gitlab on my machine. 
docker-compose up -d gitlab and its starting but the status is up {int} seconds (health: starting) after awhile its exited. 
I check the logs docker-compose logs gitlab i got an error
Error executing action `create` on resource 'storage_directory[/var/opt/gitlab/.ssh]'
_____

### Expected behavior:
Start/Run gitlab on local machine
_____

### Reproduce:

docker-compose up -d gitlab
_____

### Relevant Code:

`gitlab_1               |     Error executing action `create` on resource 'storage_directory[/var/opt/gitlab/.ssh]'
gitlab_1               |     ================================================================================
gitlab_1               |
gitlab_1               |     Mixlib::ShellOut::ShellCommandFailed
gitlab_1               |     ------------------------------------
gitlab_1               |     ruby_block[directory resource: /var/opt/gitlab/.ssh] (/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb line 33) had an error: Mixlib::ShellOut::ShellCommandFailed: Failed asserting that ownership of "/var/opt/gitlab/.ssh" was git:git
gitlab_1               |     ---- Begin output of set -x && [ "$(stat --printf='%U:%G' $(readlink -f /var/opt/gitlab/.ssh))" = 'git:git' ] ----
gitlab_1               |     STDOUT:
gitlab_1               |     STDERR: + readlink -f /var/opt/gitlab/.ssh
gitlab_1               |     + stat --printf=%U:%G /var/opt/gitlab/.ssh
gitlab_1               |     + [ root:root = git:git ]
gitlab_1               |     ---- End output of set -x && [ "$(stat --printf='%U:%G' $(readlink -f /var/opt/gitlab/.ssh))" = 'git:git' ] ----
gitlab_1               |     Ran set -x && [ "$(stat --printf='%U:%G' $(readlink -f /var/opt/gitlab/.ssh))" = 'git:git' ] returned 1
gitlab_1               |
gitlab_1               |     Cookbook Trace:
gitlab_1               |     ---------------
gitlab_1               |     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:125:in `validate_command'
gitlab_1               |     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:113:in `block in validate'
gitlab_1               |     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:112:in `each_index'
gitlab_1               |     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:112:in `validate'
gitlab_1               |     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:87:in `validate!'
gitlab_1               |     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb:42:in `block (3 levels) in class_from_file'
gitlab_1               |
gitlab_1               |     Resource Declaration:
gitlab_1               |     ---------------------
gitlab_1               |     # In /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/gitlab-shell.rb
gitlab_1               |
gitlab_1               |      38:   storage_directory dir do
gitlab_1               |      39:     owner git_user
gitlab_1               |      40:     group git_group
gitlab_1               |      41:     mode "0700"
gitlab_1               |      42:   end
gitlab_1               |      43: end
gitlab_1               |
gitlab_1               |     Compiled Resource:
gitlab_1               |     ------------------
gitlab_1               |     # Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/gitlab-shell.rb:38:in `block in from_file'
gitlab_1               |
gitlab_1               |     storage_directory("/var/opt/gitlab/.ssh") do
gitlab_1               |       action [:create]
gitlab_1               |       default_guard_interpreter :default
gitlab_1               |       declared_type :storage_directory
gitlab_1               |       cookbook_name "gitlab"
gitlab_1               |       recipe_name "gitlab-shell"
gitlab_1               |       owner "git"
gitlab_1               |       group "git"
gitlab_1               |       mode "0700"
gitlab_1               |       path "/var/opt/gitlab/.ssh"
gitlab_1               |     end
gitlab_1               |
gitlab_1               |     System Info:
gitlab_1               |     ------------
gitlab_1               |     chef_version=13.6.4
gitlab_1               |     platform=ubuntu
gitlab_1               |     platform_version=16.04
gitlab_1               |     ruby=ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
gitlab_1               |     program_name=/opt/gitlab/embedded/bin/chef-client
gitlab_1               |     executable=/opt/gitlab/embedded/bin/chef-client
gitlab_1               |
gitlab_1               |
gitlab_1               | Running handlers:
gitlab_1               | There was an error running gitlab-ctl reconfigure:
gitlab_1               |
gitlab_1               | storage_directory[/var/opt/gitlab/.ssh] (gitlab::gitlab-shell line 38) had an error: Mixlib::ShellOut::ShellCommandFailed:
ruby_block[directory resource: /var/opt/gitlab/.ssh] (/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb line 33) had an error: Mixlib::ShellOut::ShellCommandFailed: Failed asserting that ownership of "/var/opt/gitlab/.ssh" was git:git
gitlab_1               | ---- Begin output of set -x && [ "$(stat --printf='%U:%G' $(readlink -f /var/opt/gitlab/.ssh))" = 'git:git' ] ----
gitlab_1               | STDOUT:
gitlab_1               | STDERR: + readlink -f /var/opt/gitlab/.ssh
gitlab_1               | + stat --printf=%U:%G /var/opt/gitlab/.ssh
gitlab_1               | + [ root:root = git:git ]
gitlab_1               | ---- End output of set -x && [ "$(stat --printf='%U:%G' $(readlink -f /var/opt/gitlab/.ssh))" = 'git:git' ] ----
gitlab_1               | Ran set -x && [ "$(stat --printf='%U:%G' $(readlink -f /var/opt/gitlab/.ssh))" = 'git:git' ] returned 1
gitlab_1               |
gitlab_1               | Running handlers complete
gitlab_1               | Chef Client failed. 3 resources updated in 10 seconds`

**Comment by sanpakyou027** [comment]
duplicate issue
