### ISSUE TITLE
npm run dev error - Node Sass does not yet support your current environment

### ISSUE THREAD

**Issue by ndberg** [laradock/laradock#1898]
### Info:
- Docker version (`$ docker --version`):  Docker version 18.09.0, build 4d60db4
- Laradock commit (`$ git rev-parse HEAD`): bee066c5804b8d47aa3130c7825cb4b2cf9d03d2
- System info (Mac, PC, Linux): Mac
- System info disto/version: macOS Mojave 10.14.1

### Issue:
Can't run npm run dev in workspace container
_____

### Expected behavior:
Should compile js + sass
_____

### Reproduce:
Don't know
_____

### Relevant Code:

```
npm run dev
... some stuff okay but then ...
ERROR in ./resources/sass/main-layout.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.4
    at module.exports (/var/www/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/var/www/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/var/www/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadLoader (/var/www/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/var/www/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/var/www/node_modules/webpack/lib/NormalModule.js:275:15)
    at runLoaders (/var/www/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/var/www/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/var/www/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/var/www/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/var/www/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/var/www/node_modules/webpack/lib/Compilation.js:157:10)
    at moduleFactory.create (/var/www/node_modules/webpack/lib/Compilation.js:460:10)
    at factory (/var/www/node_modules/webpack/lib/NormalModuleFactory.js:243:5)
    at applyPluginsAsyncWaterfall (/var/www/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /var/www/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/var/www/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/var/www/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/var/www/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/var/www/node_modules/webpack/lib/NormalModuleFactory.js:196:7)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
 @ ./resources/sass/main-layout.scss
 @ multi ./resources/js/bootstrap.js ./resources/sass/firma.scss ./resources/sass/admin.scss ./resources/sass/pdf.scss ./resources/sass/umzug-desktop.scss ./resources/sass/umzug-tablet.scss ./resources/sass/umzug-mobile.scss ./resources/sass/reinigung-desktop.scss ./resources/sass/reinigung-tablet.scss ./resources/sass/reinigung-mobile.scss ./resources/sass/maler-desktop.scss ./resources/sass/maler-tablet.scss ./resources/sass/maler-mobile.scss ./resources/sass/catering-desktop.scss ./resources/sass/main-layout.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/laradock/.npm/_logs/2018-11-28T13_05_57_856Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/laradock/.npm/_logs/2018-11-28T13_05_57_880Z-debug.log

```

**Comment by ryancwalsh** [comment]
Did you ever solve this? I'm having the same problem. I thought https://stackoverflow.com/a/37690218/470749 might help, but it hasn't. Thanks.

**Comment by tomvo** [comment]
@ryancwalsh @ndberg For me the solution was to downgrade node to `8.16.0`

**Comment by internetfett** [comment]
I'm still having this issue.

**Comment by jeremynikolic** [comment]
Encountered this issue too and for now my solution is to go with yarn instead of npm
