### ISSUE TITLE
Elasticsearch version change error

### ISSUE THREAD

**Issue by leyoug** [laradock/laradock#2080]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): c4aef8e901a867a57df0b1aadf1c872165e65295
- System info (Mac, PC, Linux): window 10
- System info disto/version: 

### Issue:

_____
Can not run elasticsearch container

1. I changed the version 5.4.1 to 6.0.1
elasticsearch/Dockerfile
`FROM docker.elastic.co/elasticsearch/elasticsearch:6.0.1`

2.
```
docker-compose build elasticsearch
docker-compose up -d elasticsearch
```

```
elasticsearch_1        | 2019-04-09T07:42:59.617228200Z [2019-04-09T07:42:59,596][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1        | 2019-04-09T07:42:59.617273700Z org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [ingest-user-agent] is incompatible with version [6.0.1]; was designed for version [5.4.1]
elasticsearch_1        | 2019-04-09T07:42:59.617278900Z         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:134) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617317400Z         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:121) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617320600Z         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617323200Z         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617325800Z         at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617328300Z         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617330800Z         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617333400Z Caused by: java.lang.IllegalArgumentException: plugin [ingest-user-agent] is incompatible with version [6.0.1]; was designed for version [5.4.1]
elasticsearch_1        | 2019-04-09T07:42:59.617336000Z         at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:155) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617338500Z         at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:80) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617341000Z         at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:166) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617343500Z         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617346100Z         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:42:59.617348600Z         ... 6 more
elasticsearch_1        | 2019-04-09T07:44:10.581285800Z [2019-04-09T07:44:10,577][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1        | 2019-04-09T07:44:10.581323100Z org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [ingest-user-agent] is incompatible with version [6.0.1]; was designed for version [5.4.1]
elasticsearch_1        | 2019-04-09T07:44:10.581328800Z         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:134) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581332500Z         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:121) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581335700Z         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581338800Z         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581341900Z         at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581351300Z         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581354400Z         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581357200Z Caused by: java.lang.IllegalArgumentException: plugin [ingest-user-agent] is incompatible with version [6.0.1]; was designed for version [5.4.1]
elasticsearch_1        | 2019-04-09T07:44:10.581360000Z         at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:155) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581362800Z         at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:80) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581365400Z         at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:166) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581368000Z         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581370800Z         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130) ~[elasticsearch-6.0.1.jar:6.0.1]
elasticsearch_1        | 2019-04-09T07:44:10.581373500Z         ... 6 more
laradock_elasticsearch_1 exited with code 1
```

docker-compose.yml
```
elasticsearch:
      build: ./elasticsearch
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
        - elasticsearch-plugins:/usr/share/elasticsearch/plugins
...
elasticsearch-data:
    driver: "local"
  elasticsearch-plugins:
    driver: "local"
```

The problem is this
`plugin [ingest-user-agent] is incompatible with version [6.0.1]; was designed for version [5.4.1]`

How do I update ingest-user-agent plugin?

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by leyoug** [comment]
I checkout laradock latest version (v7.14) and use elasticsearch 6.6.0

+ can i change elasticsearch version to 6.0.1?
