### ISSUE TITLE
failed Error: not found: python2

### ISSUE THREAD

**Issue by Sogl** [laradock/laradock#2175]
### Info:
- Docker version (`$ docker --version`):  18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): 63fc1fde44cc00aacb89511a441cb83685e8010c (v. 7.15)
- System info (Mac, PC, Linux): Mac OS Sierra 10.12.6
- System info disto/version: 

### Issue:

When I tried to use `yarn` I see this error:
```
laradock@5495cb24f7b6:/var/www/blender$ yarn
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[6/6] ⠈ node-sass
[-/6] ⠈ waiting...
[3/6] ⠈ mozjpeg
[-/6] ⠈ waiting...
error /var/www/blender/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /var/www/blender/node_modules/node-sass
Output:
Building: /home/laradock/.nvm/versions/node/v12.4.0/bin/node /var/www/blender/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/laradock/.nvm/versions/node/v12.4.0/bin/node',
gyp verb cli   '/var/www/blender/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.6.2
gyp info using node@12.4.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/blender/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/blender/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/blender/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/blender/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/blender/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/blender/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/blender/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/blender/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/blender/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/blender/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/blender/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/blender/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError ' +
gyp verb `which` failed     '(/var/www/blender/node_modules/which/which.js:13:12)\n    at F ' +
gyp verb `which` failed     '(/var/www/blender/node_modules/which/which.js:68:19)\n    at E ' +
gyp verb `which` failed     '(/var/www/blender/node_modules/which/which.js:80:29)\n    at ' +
gyp verb `which` failed     '/var/www/blender/node_modules/which/which.js:89:16\n    at ' +
gyp verb `which` failed     '/var/www/blender/node_modules/isexe/index.js:42:5\n    at ' +
gyp verb `which` failed     '/var/www/blender/node_modules/isexe/mode.js:8:5\n    at ' +
gyp verb `which` failed     'FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/blender/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/blender/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/blender/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/blender/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/blender/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/blender/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/blender/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/blender/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/blender/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/blender/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/blender/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/blender/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError ' +
gyp verb `which` failed     '(/var/www/blender/node_modules/which/which.js:13:12)\n    at F ' +
gyp verb `which` failed     '(/var/www/blender/node_modules/which/which.js:68:19)\n    at E ' +
gyp verb `which` failed     '(/var/www/blender/node_modules/which/which.js:80:29)\n    at ' +
gyp verb `which` failed     '/var/www/blender/node_modules/which/which.js:89:16\n    at ' +
gyp verb `which` failed     '/var/www/blender/node_modules/isexe/index.js:42:5\n    at ' +
gyp verb `which` failed     '/var/www/blender/node_modules/isexe/mode.js:8:5\n    at ' +
gyp verb `which` failed     'FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/var/www/blender/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/blender/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/var/www/blender/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/var/www/blender/node_modules/which/which.js:80:29)
gyp ERR! stack     at /var/www/blender/node_modules/which/which.js:89:16
gyp ERR! stack     at /var/www/blender/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/blender/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:165:21)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/home/laradock/.nvm/versions/node/v12.4.0/bin/node" "/var/www/blender/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/blender/node_modules/node-sass
gyp ERR! node -v v12.4.0
```

I see that `python3` command is exist in PATH and working, but no command for `python2` or `python2.7`.

**I also found some issues and PRs but nothing works for now:**
https://github.com/laradock/laradock/issues/1238 (2017 year conversation about problem)
https://github.com/laradock/laradock/pull/1240 (add python2.7 lines)
https://github.com/laradock/laradock/pull/1257 (remove lines 😄 )

### Expected behavior:

`python2.7` is installed and `python` or `python2` commands works.

### Reproduce:

Try to install Laravel bolerplate: https://github.com/spatie/blender frontend with `yarn` command.

**Comment by Sogl** [comment]
Also I found similar issue from another repository: https://github.com/nodejs/docker-node/issues/384
Maybe I can add few lines from there `Dockerfile` to fix?

**Comment by Sogl** [comment]
Ok, solved with some steps:
1. Add `python2.7` installation line to `workspace/Dockerfile`:
```
###########################################################################
# PYTHON:
###########################################################################

ARG INSTALL_PYTHON=false

RUN if [ ${INSTALL_PYTHON} = true ]; then \
  apt-get -y install python python2.7 python-pip python-dev build-essential  \
  && python -m pip install --upgrade pip  \
  && python -m pip install --upgrade virtualenv \
;fi
```
2. Rebuild workspace container without cache (I tried with cache before with no luck): `docker-compose build --no-cache workspace`
3. Up the new container: `docker-compose up workspace`

Logs:
```
MacBook-Pro-Artem:laradock artyom$  docker-compose up workspace
laradock_docker-in-docker_1 is up-to-date
Recreating laradock_workspace_1 ... done
Attaching to laradock_workspace_1
```
I don't know how it works, but this step solved my another problem with downgrade MySQL from `latest` to `5.7`. I think it recreate links/relations with `docker-in-docker` main container and rebuilded container.

4. `Ctrl + C` to Abort. Container is still works.
5. Profit. You can now login as root with `docker-compose exec workspace bash` or with laradock user `docker-compose exec --user=laradock workspace bash` and `python` command works!

**Comment by ledtest** [comment]
> Ok, solved with some steps:
> 
> 1. Add `python2.7` installation line to `workspace/Dockerfile`:
> 
> ```
> ###########################################################################
> # PYTHON:
> ###########################################################################
> 
> ARG INSTALL_PYTHON=false
> 
> RUN if [ ${INSTALL_PYTHON} = true ]; then \
>   apt-get -y install python python2.7 python-pip python-dev build-essential  \
>   && python -m pip install --upgrade pip  \
>   && python -m pip install --upgrade virtualenv \
> ;fi
> ```
> 
> 1. Rebuild workspace container without cache (I tried with cache before with no luck): `docker-compose build --no-cache workspace`
> 2. Up the new container: `docker-compose up workspace`
> 
> Logs:
> 
> ```
> MacBook-Pro-Artem:laradock artyom$  docker-compose up workspace
> laradock_docker-in-docker_1 is up-to-date
> Recreating laradock_workspace_1 ... done
> Attaching to laradock_workspace_1
> ```
> 
> I don't know how it works, but this step solved my another problem with downgrade MySQL from `latest` to `5.7`. I think it recreate links/relations with `docker-in-docker` main container and rebuilded container.
> 
> 1. `Ctrl + C` to Abort. Container is still works.
> 2. Profit. You can now login as root with `docker-compose exec workspace bash` or with laradock user `docker-compose exec --user=laradock workspace bash` and `python` command works!

Thank you very much. Your answer solved my problem. Now node works very well.
