### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by NetBT** [laradock/laradock#2237]
### Info:
- Docker version : 19.03.1, build 74b1e89
- Laradock commit : 493fc1a01047f285fb2bc768dbbaf62fdd804e02
- System info : PC
- System info disto/version: WIN10 pro 1809

### Issue:
An error occurred while I visit laravel-echo-server by localhost:6001.
_____

### Expected behavior:
TypeError: Cannot read property 'options' of undefined
    at /usr/src/app/node_modules/laravel-echo-server/dist/server.js:60:37
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/src/app/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/src/app/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
_____

### Reproduce:
Build a laravel-echo-server,and visit localhost:6001.
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by NetBT** [comment]
The latest laravel-echo-server fixed this problem.[laravel-echo-server:issues#430](https://github.com/tlaverdure/laravel-echo-server/issues/430)
