### ISSUE TITLE
Errow when docker-compose exec workspace bash

### ISSUE THREAD

**Issue by ezekel** [laradock/laradock#2477]
Docker version 19.03.5, build 633a0ea
Docker Desktop Commpunity 2.2.0.0(42247)

After executing the docker-compose exec workspace bash
this is what I got 

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[19720] Failed to execute script docker-compose

```

please help how to fix this

**Comment by hareku** [comment]
@ezekel 
This problem was fixed in docker-compose@`1.25.3`.
https://github.com/docker/compose/issues/7169#issuecomment-577897868

Please upgrade your docker-compose version.

**Comment by ezekel** [comment]
@hareku ,

Thank you for the quick reply, I tried to git pull to my laradock folder, I was not able to see your reply before I ran git pull.


here is another error

```
he LARAVEL_HORIZON_INSTALL_PHPREDIS variable is not set. Defaulting to a blank string.
The LARAVEL_HORIZON_INSTALL_MONGO variable is not set. Defaulting to a blank string.
The LARAVEL_HORIZON_INSTALL_FFMPEG variable is not set. Defaulting to a blank string.
The PHP_FPM_INSTALL_PCOV variable is not set. Defaulting to a blank string.
The PHP_FPM_INSTALL_SMB variable is not set. Defaulting to a blank string.
The PHP_FPM_INSTALL_GEARMAN variable is not set. Defaulting to a blank string.
The PHP_FPM_INSTALL_OCI8 variable is not set. Defaulting to a blank string.
The PHP_FPM_INSTALL_CACHETOOL variable is not set. Defaulting to a blank string.
The PHP_FPM_INSTALL_GETTEXT variable is not set. Defaulting to a blank string.
The PHP_FPM_INSTALL_MAILPARSE variable is not set. Defaulting to a blank string.
The PHP_FPM_PUID variable is not set. Defaulting to a blank string.
The PHP_FPM_PGID variable is not set. Defaulting to a blank string.
The PHP_FPM_DEFAULT_LOCALE variable is not set. Defaulting to a blank string.
The PHP_WORKER_INSTALL_GEARMAN variable is not set. Defaulting to a blank string.
The PHP_WORKER_INSTALL_REDIS variable is not set. Defaulting to a blank string.
The GEARMAN_VERSION variable is not set. Defaulting to a blank string.
The GEARMAN_VERBOSE variable is not set. Defaulting to a blank string.
The GEARMAN_QUEUE_TYPE variable is not set. Defaulting to a blank string.
The GEARMAN_THREADS variable is not set. Defaulting to a blank string.
The GEARMAN_BACKLOG variable is not set. Defaulting to a blank string.
The GEARMAN_FILE_DESCRIPTORS variable is not set. Defaulting to a blank string.
The GEARMAN_JOB_RETRIES variable is not set. Defaulting to a blank string.
The GEARMAN_ROUND_ROBIN variable is not set. Defaulting to a blank string.
The GEARMAN_WORKER_WAKEUP variable is not set. Defaulting to a blank string.
The GEARMAN_KEEPALIVE variable is not set. Defaulting to a blank string.
The GEARMAN_KEEPALIVE_IDLE variable is not set. Defaulting to a blank string.
The GEARMAN_KEEPALIVE_INTERVAL variable is not set. Defaulting to a blank string.
The GEARMAN_KEEPALIVE_COUNT variable is not set. Defaulting to a blank string.
The GEARMAN_MYSQL_HOST variable is not set. Defaulting to a blank string.
The GEARMAN_MYSQL_PORT variable is not set. Defaulting to a blank string.
The GEARMAN_MYSQL_USER variable is not set. Defaulting to a blank string.
The GEARMAN_MYSQL_PASSWORD variable is not set. Defaulting to a blank string.
The GEARMAN_MYSQL_PASSWORD_FILE variable is not set. Defaulting to a blank string.
The GEARMAN_MYSQL_DB variable is not set. Defaulting to a blank string.
The GEARMAN_MYSQL_TABLE variable is not set. Defaulting to a blank string.
The GEARMAN_PORT variable is not set. Defaulting to a blank string.
The TOMCAT_VERSION variable is not set. Defaulting to a blank string.
The TOMCAT_HOST_HTTP_PORT variable is not set. Defaulting to a blank string.
The UBUNTU_SOURCE variable is not set. Defaulting to a blank string.
The WORKSPACE_INSTALL_PCOV variable is not set. Defaulting to a blank string.
The WORKSPACE_INSTALL_SMB variable is not set. Defaulting to a blank string.
The WORKSPACE_INSTALL_GEARMAN variable is not set. Defaulting to a blank string.
The WORKSPACE_NVM_NODEJS_ORG_MIRROR variable is not set. Defaulting to a blank string.
The WORKSPACE_INSTALL_OCI8 variable is not set. Defaulting to a blank string.
The WORKSPACE_INSTALL_AST variable is not set. Defaulting to a blank string.
The WORKSPACE_INSTALL_YAML variable is not set. Defaulting to a blank string.
The WORKSPACE_INSTALL_MAILPARSE variable is not set. Defaulting to a blank string.
The WORKSPACE_AST_VERSION variable is not set. Defaulting to a blank string.
The WORKSPACE_INSTALL_SUPERVISOR variable is not set. Defaulting to a blank string.
The Compose file '.\docker-compose.yml' is invalid because:
services.gearman.ports is invalid: Port ranges don't match in length
services.tomcat.ports is invalid: Port ranges don't match in length
```

**Comment by ezekel** [comment]
downloading now hope it will work

**Comment by ezekel** [comment]
I was downloading the Docker Desktop Installer ? but when I ran it says already up to date

**Comment by ezekel** [comment]
@hareku ,

you mean `curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose` ?

**Comment by ezekel** [comment]
@hareku ,

I run this docker-compose-Windows-x86_64.exe, but it only open small balck window then disappear
please help.

**Comment by ezekel** [comment]
Is this the version docker-compose version 1.25.2, build 698e2846 ?

**Comment by ezekel** [comment]
Thank you it works,

I downloaded the `docker-compose-Windows-x86_64` and renamed it to `docker-compose`
and over write the docker-compose.exe on this folder 
`C:\Program Files\Docker\Docker\resources\bin`
restart docker.
chadang.... :)

Happy Coding :)
