### ISSUE TITLE
yarn cannot be used in 'WORKSPACE'

### ISSUE THREAD

**Issue by sesameguy** [laradock/laradock#2615]
I have entered the container by `docker-compose exec workspace bash` & use `yarn`
but the below message is shown
```console
❯ yarn
Error: ENOTDIR: not a directory, open '/root/.config/yarn/config'
    at Object.openSync (fs.js:461:3)
    at readFileSync (fs.js:364:35)
    at /home/laradock/.yarn/lib/cli.js:101331:58
    at Array.map (<anonymous>)
    at parseRcPaths (/home/laradock/.yarn/lib/cli.js:101329:78)
    at Object.findRc (/home/laradock/.yarn/lib/cli.js:101343:10)
    at getRcConfigForCwd (/home/laradock/.yarn/lib/cli.js:56915:74)
    at /home/laradock/.yarn/lib/cli.js:92694:56
    at Generator.next (<anonymous>)
    at step (/home/laradock/.yarn/lib/cli.js:310:30)
```

**Comment by bestlong** [comment]
is work on mac

<img width="716" alt="截圖 2020-06-13 19 13 11" src="https://user-images.githubusercontent.com/4023909/84567258-064d5b80-adaa-11ea-80c2-9003d0e04168.png">
