### ISSUE TITLE
Run pgadmin ERROR

### ISSUE THREAD

**Issue by pozxnm123** [laradock/laradock#2636]
### Context information:

**Output of `git rev-parse HEAD`**

```
41ad5527daee2a2f57373d5500e556dfe51b62fb
```

**Output of `docker version`**

```
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose version`**

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Ubuntu 18.04
```

### Steps to reproduce the issue:

1. run pgadmin error

### Stacktrace & Additional info:

```
[2020-06-18 14:01:58 +0000] [83] [INFO] Booting worker with pid: 83
[2020-06-18 14:01:58 +0000] [83] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 92, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 241, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
    _create_directory_if_not_exists(config.SESSION_DB_PATH)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
[2020-06-18 14:01:58 +0000] [83] [INFO] Worker exiting (pid: 83)
WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
```

**Comment by bestlong** [comment]
if .env `DATA_PATH_HOST=~/.laradock/data`

check file system Permission

<img width="623" alt="截圖 2020-06-19 00 07 29" src="https://user-images.githubusercontent.com/4023909/85045075-13f74c80-b1c1-11ea-8d54-1c784655e4bf.png">

or run `rm -rf ~/.laradock/data/pgadmin` and up pgadmin again.

**Comment by pozxnm123** [comment]
> 如果.env `DATA_PATH_HOST=~/.laradock/data`
> 
> 檢查文件系統權限
> 
> <img alt="截圖2020-06-19 00 07 29" width="623" src="https://user-images.githubusercontent.com/4023909/85045075-13f74c80-b1c1-11ea-8d54-1c784655e4bf.png">
> 
> 或`rm -rf ~/.laradock/data/pgadmin`再次運行並啟動pgadmin。

Thank 

Is a problem with system permissions

**Comment by pozxnm123** [comment]
> if .env `DATA_PATH_HOST=~/.laradock/data`
> 
> check file system Permission
> 
> <img alt="截圖 2020-06-19 00 07 29" width="623" src="https://user-images.githubusercontent.com/4023909/85045075-13f74c80-b1c1-11ea-8d54-1c784655e4bf.png">
> 
> or run `rm -rf ~/.laradock/data/pgadmin` and up pgadmin again.

Thank

Is a problem with system permissions
