### ISSUE TITLE
Workspace Build Bug

### ISSUE THREAD

**Issue by prezire** [laradock/laradock#2827]
### Description:

Python invalid syntax error, which I think is similar to this https://issuehunt.io/r/laradock/laradock/issues/1496.
This also happened on AWS CodeBuild.

### Expected Behavior:

Successful build of **workspace** image.

### Context information:

**Output of `git rev-parse HEAD`**
```
The entire LaraDock framework was merged into the project as per preference. So this is N/A.
The framework was first used on March 2020. But I believe the version is v9.4-2-g0d08602 or possibly earlier.
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
```

### Steps to reproduce the issue:

1. docker-compose up -d workspace or docker-compose build --no-cache workspace

### Stacktrace & Additional info:

```
Collecting pip
  Downloading https://files.pythonhosted.org/packages/9e/24/bc928987f35dd0167f21b13a1777c21b9c5917c9894cff93f1c1a6cb8f3b/pip-21.0.tar.gz (1.5MB)
Building wheels for collected packages: pip
  Running setup.py bdist_wheel for pip: started
  Running setup.py bdist_wheel for pip: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/d8/d0/57/01dfab821d34e9454331e6002c17f9d5f5939800798f7fbc50
Successfully built pip
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-21.0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by prezire** [comment]
Update:
I commented the line `#&& python -m pip install --upgrade virtualenv \` and the error now moved to `python -m pip install --upgrade supervisor && \` under $INSTALL_SUPERVISOR.

**Comment by jmourell** [comment]
I am having the same issue

**Comment by jmourell** [comment]
Hi prezire,
I think it's an issue with python2 and python3. If you you change your .env file 
WORKSPACE_INSTALL_PYTHON=false
WORKSPACE_INSTALL_PYTHON3=true
to use python3 it builds fine from there

**Comment by millman2394** [comment]
same issue

**Comment by pro100taA** [comment]
`ARG INSTALL_PYTHON=false

RUN if [ ${INSTALL_PYTHON} = true ]; then \
  apt-get -y install python python-dev build-essential  \
  && curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py \
  && python get-pip.py \
  && python -m pip install --upgrade pip  \
  && python -m pip install --upgrade virtualenv \
;fi
`
fix

**Comment by Sogl** [comment]
Same issue but @pro100taA code helped me.
