### ISSUE TITLE
Failed to install imagemagick: Permission denied on pycache dir

### ISSUE THREAD

**Issue by Tannenfels** [laradock/laradock#3396]
### Context information:

**Output of `git rev-parse HEAD`**

```
998089bf3de40e5dfdf0887f6b52f858b380fc1b
```

**Output of `docker version`**

```
20.10.21
```

**Output of `docker-compose version`**

```
1.29.2
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Ubuntu Linux
```

### Steps to reproduce the issue:

1. Set `WORKSPACE_INSTALL_IMAGEMAGICK` to `true`.
2. `docker-compose up -d php-fpm`

### Stacktrace & Additional info:

```
Step 103/200 : USER root
 ---> Using cache
 ---> 0801bccc577f
Step 104/200 : ARG INSTALL_IMAGEMAGICK=false
 ---> Using cache
 ---> 2715c147d510
Step 105/200 : ARG IMAGEMAGICK_VERSION=latest
 ---> Using cache
 ---> d65eb93662c9
Step 106/200 : ENV IMAGEMAGICK_VERSION ${IMAGEMAGICK_VERSION}
 ---> Using cache
 ---> f9064cce20bb
Step 107/200 : RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then     apt-get install -yqq libmagickwand-dev imagemagick &&     if [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then       cd /tmp &&       if [ ${IMAGEMAGICK_VERSION} = "latest" ]; then         git clone https://github.com/Imagick/imagick;       else         git clone --branch ${IMAGEMAGICK_VERSION} https://github.com/Imagick/imagick;       fi &&       cd imagick &&       phpize &&       ./configure &&       make &&       make install &&       rm -r /tmp/imagick;     else       pecl install imagick;     fi &&     docker-php-ext-enable imagick;     php -m | grep -q 'imagick' ;fi
 ---> Running in ab5c82d1e44f
Preconfiguring packages ...
Selecting previously unselected package libapparmor1:amd64.
(Reading database ... 16541 files and directories currently installed.)
Preparing to unpack .../00-libapparmor1_2.13.6-10_amd64.deb ...
Unpacking libapparmor1:amd64 (2.13.6-10) ...
Selecting previously unselected package libdbus-1-3:amd64.
Preparing to unpack .../01-libdbus-1-3_1.12.24-0+deb11u1_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.12.24-0+deb11u1) ...
Selecting previously unselected package dbus.
Preparing to unpack .../02-dbus_1.12.24-0+deb11u1_amd64.deb ...
Unpacking dbus (1.12.24-0+deb11u1) ...
Selecting previously unselected package fonts-droid-fallback.
Preparing to unpack .../03-fonts-droid-fallback_1%3a6.0.1r16-1.1_all.deb ...
Unpacking fonts-droid-fallback (1:6.0.1r16-1.1) ...
Selecting previously unselected package imagemagick-6-common.
Preparing to unpack .../04-imagemagick-6-common_8%3a6.9.11.60+dfsg-1.3+deb11u1_all.deb ...
Unpacking imagemagick-6-common (8:6.9.11.60+dfsg-1.3+deb11u1) ...
Selecting previously unselected package libmagickcore-6-headers.
Preparing to unpack .../05-libmagickcore-6-headers_8%3a6.9.11.60+dfsg-1.3+deb11u1_all.deb ...
Unpacking libmagickcore-6-headers (8:6.9.11.60+dfsg-1.3+deb11u1) ...
Selecting previously unselected package libmagickcore-6-arch-config:amd64.
Preparing to unpack .../06-libmagickcore-6-arch-config_8%3a6.9.11.60+dfsg-1.3+deb11u1_amd64.deb ...
Unpacking libmagickcore-6-arch-config:amd64 (8:6.9.11.60+dfsg-1.3+deb11u1) ...
Selecting previously unselected package libfftw3-double3:amd64.
Preparing to unpack .../07-libfftw3-double3_3.3.8-2_amd64.deb ...
Unpacking libfftw3-double3:amd64 (3.3.8-2) ...
Selecting previously unselected package sensible-utils.
Preparing to unpack .../08-sensible-utils_0.0.14_all.deb ...
Unpacking sensible-utils (0.0.14) ...
Selecting previously unselected package ucf.
Preparing to unpack .../09-ucf_3.0043_all.deb ...
Moving old data out of the way
Unpacking ucf (3.0043) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../10-fonts-dejavu-core_2.37-2_all.deb ...
Unpacking fonts-dejavu-core (2.37-2) ...
Selecting previously unselected package fonts-urw-base35.
Preparing to unpack .../11-fonts-urw-base35_20200910-1_all.deb ...
Unpacking fonts-urw-base35 (20200910-1) ...
Selecting previously unselected package fontconfig-config.
Preparing to unpack .../12-fontconfig-config_2.13.1-4.2_all.deb ...
Unpacking fontconfig-config (2.13.1-4.2) ...
Selecting previously unselected package libfontconfig1:amd64.
Preparing to unpack .../13-libfontconfig1_2.13.1-4.2_amd64.deb ...
Unpacking libfontconfig1:amd64 (2.13.1-4.2) ...
Selecting previously unselected package libaom0:amd64.
Preparing to unpack .../14-libaom0_1.0.0.errata1-3_amd64.deb ...
Unpacking libaom0:amd64 (1.0.0.errata1-3) ...
Selecting previously unselected package libdav1d4:amd64.
Preparing to unpack .../15-libdav1d4_0.7.1-3_amd64.deb ...
Unpacking libdav1d4:amd64 (0.7.1-3) ...
Selecting previously unselected package libde265-0:amd64.
Preparing to unpack .../16-libde265-0_1.0.11-0+deb11u1_amd64.deb ...
Unpacking libde265-0:amd64 (1.0.11-0+deb11u1) ...
Selecting previously unselected package libnuma1:amd64.
Preparing to unpack .../17-libnuma1_2.0.12-1+b1_amd64.deb ...
Unpacking libnuma1:amd64 (2.0.12-1+b1) ...
Selecting previously unselected package libx265-192:amd64.
Preparing to unpack .../18-libx265-192_3.4-2_amd64.deb ...
Unpacking libx265-192:amd64 (3.4-2) ...
Selecting previously unselected package libheif1:amd64.
Preparing to unpack .../19-libheif1_1.11.0-1_amd64.deb ...
Unpacking libheif1:amd64 (1.11.0-1) ...
Selecting previously unselected package libjbig0:amd64.
Preparing to unpack .../20-libjbig0_2.1-3.1+b2_amd64.deb ...
Unpacking libjbig0:amd64 (2.1-3.1+b2) ...
Selecting previously unselected package liblcms2-2:amd64.
Preparing to unpack .../21-liblcms2-2_2.12~rc1-2_amd64.deb ...
Unpacking liblcms2-2:amd64 (2.12~rc1-2) ...
Selecting previously unselected package liblqr-1-0:amd64.
Preparing to unpack .../22-liblqr-1-0_0.4.2-2.1_amd64.deb ...
Unpacking liblqr-1-0:amd64 (0.4.2-2.1) ...
Selecting previously unselected package libltdl7:amd64.
Preparing to unpack .../23-libltdl7_2.4.6-15_amd64.deb ...
Unpacking libltdl7:amd64 (2.4.6-15) ...
Selecting previously unselected package libopenjp2-7:amd64.
Preparing to unpack .../24-libopenjp2-7_2.4.0-3_amd64.deb ...
Unpacking libopenjp2-7:amd64 (2.4.0-3) ...
Selecting previously unselected package libdeflate0:amd64.
Preparing to unpack .../25-libdeflate0_1.7-1_amd64.deb ...
Unpacking libdeflate0:amd64 (1.7-1) ...
Selecting previously unselected package libtiff5:amd64.
Preparing to unpack .../26-libtiff5_4.2.0-1+deb11u4_amd64.deb ...
Unpacking libtiff5:amd64 (4.2.0-1+deb11u4) ...
Selecting previously unselected package libmagickcore-6.q16-6:amd64.
Preparing to unpack .../27-libmagickcore-6.q16-6_8%3a6.9.11.60+dfsg-1.3+deb11u1_amd64.deb ...
Unpacking libmagickcore-6.q16-6:amd64 (8:6.9.11.60+dfsg-1.3+deb11u1) ...
Selecting previously unselected package libpixman-1-0:amd64.
Preparing to unpack .../28-libpixman-1-0_0.40.0-1.1~deb11u1_amd64.deb ...
Unpacking libpixman-1-0:amd64 (0.40.0-1.1~deb11u1) ...
Selecting previously unselected package libxcb-render0:amd64.
Preparing to unpack .../29-libxcb-render0_1.14-3_amd64.deb ...
Unpacking libxcb-render0:amd64 (1.14-3) ...
Selecting previously unselected package libxcb-shm0:amd64.
Preparing to unpack .../30-libxcb-shm0_1.14-3_amd64.deb ...
Unpacking libxcb-shm0:amd64 (1.14-3) ...
Selecting previously unselected package libxrender1:amd64.
Preparing to unpack .../31-libxrender1_1%3a0.9.10-1_amd64.deb ...
Unpacking libxrender1:amd64 (1:0.9.10-1) ...
Selecting previously unselected package libcairo2:amd64.
Preparing to unpack .../32-libcairo2_1.16.0-5_amd64.deb ...
Unpacking libcairo2:amd64 (1.16.0-5) ...
Selecting previously unselected package libdjvulibre-text.
Preparing to unpack .../33-libdjvulibre-text_3.5.28-2_all.deb ...
Unpacking libdjvulibre-text (3.5.28-2) ...
Selecting previously unselected package libdjvulibre21:amd64.
Preparing to unpack .../34-libdjvulibre21_3.5.28-2_amd64.deb ...
Unpacking libdjvulibre21:amd64 (3.5.28-2) ...
Selecting previously unselected package libmagickwand-6.q16-6:amd64.
Preparing to unpack .../35-libmagickwand-6.q16-6_8%3a6.9.11.60+dfsg-1.3+deb11u1_amd64.deb ...
Unpacking libmagickwand-6.q16-6:amd64 (8:6.9.11.60+dfsg-1.3+deb11u1) ...
Selecting previously unselected package libilmbase25:amd64.
Preparing to unpack .../36-libilmbase25_2.5.4-1_amd64.deb ...
Unpacking libilmbase25:amd64 (2.5.4-1) ...
Selecting previously unselected package libopenexr25:amd64.
Preparing to unpack .../37-libopenexr25_2.5.4-2+deb11u1_amd64.deb ...
Unpacking libopenexr25:amd64 (2.5.4-2+deb11u1) ...
Selecting previously unselected package fontconfig.
Preparing to unpack .../38-fontconfig_2.13.1-4.2_amd64.deb ...
Unpacking fontconfig (2.13.1-4.2) ...
Selecting previously unselected package libfribidi0:amd64.
Preparing to unpack .../39-libfribidi0_1.0.8-2+deb11u1_amd64.deb ...
Unpacking libfribidi0:amd64 (1.0.8-2+deb11u1) ...
Selecting previously unselected package libgraphite2-3:amd64.
Preparing to unpack .../40-libgraphite2-3_1.3.14-1_amd64.deb ...
Unpacking libgraphite2-3:amd64 (1.3.14-1) ...
Selecting previously unselected package libharfbuzz0b:amd64.
Preparing to unpack .../41-libharfbuzz0b_2.7.4-1_amd64.deb ...
Unpacking libharfbuzz0b:amd64 (2.7.4-1) ...
Selecting previously unselected package libthai-data.
Preparing to unpack .../42-libthai-data_0.1.28-3_all.deb ...
Unpacking libthai-data (0.1.28-3) ...
Selecting previously unselected package libdatrie1:amd64.
Preparing to unpack .../43-libdatrie1_0.2.13-1_amd64.deb ...
Unpacking libdatrie1:amd64 (0.2.13-1) ...
Selecting previously unselected package libthai0:amd64.
Preparing to unpack .../44-libthai0_0.1.28-3_amd64.deb ...
Unpacking libthai0:amd64 (0.1.28-3) ...
Selecting previously unselected package libpango-1.0-0:amd64.
Preparing to unpack .../45-libpango-1.0-0_1.46.2-3_amd64.deb ...
Unpacking libpango-1.0-0:amd64 (1.46.2-3) ...
Selecting previously unselected package libpangoft2-1.0-0:amd64.
Preparing to unpack .../46-libpangoft2-1.0-0_1.46.2-3_amd64.deb ...
Unpacking libpangoft2-1.0-0:amd64 (1.46.2-3) ...
Selecting previously unselected package libpangocairo-1.0-0:amd64.
Preparing to unpack .../47-libpangocairo-1.0-0_1.46.2-3_amd64.deb ...
Unpacking libpangocairo-1.0-0:amd64 (1.46.2-3) ...
Selecting previously unselected package libwmf0.2-7:amd64.
Preparing to unpack .../48-libwmf0.2-7_0.2.8.4-17_amd64.deb ...
Unpacking libwmf0.2-7:amd64 (0.2.8.4-17) ...
Selecting previously unselected package libmagickcore-6.q16-6-extra:amd64.
Preparing to unpack .../49-libmagickcore-6.q16-6-extra_8%3a6.9.11.60+dfsg-1.3+deb11u1_amd64.deb ...
Unpacking libmagickcore-6.q16-6-extra:amd64 (8:6.9.11.60+dfsg-1.3+deb11u1) ...
Selecting previously unselected package libbz2-dev:amd64.
Preparing to unpack .../50-libbz2-dev_1.0.8-4_amd64.deb ...
Unpacking libbz2-dev:amd64 (1.0.8-4) ...
Selecting previously unselected package libdjvulibre-dev:amd64.
Preparing to unpack .../51-libdjvulibre-dev_3.5.28-2_amd64.deb ...
Unpacking libdjvulibre-dev:amd64 (3.5.28-2) ...
Selecting previously unselected package libexif12:amd64.
Preparing to unpack .../52-libexif12_0.6.22-3_amd64.deb ...
Unpacking libexif12:amd64 (0.6.22-3) ...
Selecting previously unselected package libexif-dev:amd64.
Preparing to unpack .../53-libexif-dev_0.6.22-3_amd64.deb ...
Unpacking libexif-dev:amd64 (0.6.22-3) ...
Selecting previously unselected package libopenjp2-7-dev.
Preparing to unpack .../54-libopenjp2-7-dev_2.4.0-3_amd64.deb ...
Unpacking libopenjp2-7-dev (2.4.0-3) ...
Selecting previously unselected package liblcms2-dev:amd64.
Preparing to unpack .../55-liblcms2-dev_2.12~rc1-2_amd64.deb ...
Unpacking liblcms2-dev:amd64 (2.12~rc1-2) ...
Selecting previously unselected package liblqr-1-0-dev:amd64.
Preparing to unpack .../56-liblqr-1-0-dev_0.4.2-2.1_amd64.deb ...
Unpacking liblqr-1-0-dev:amd64 (0.4.2-2.1) ...
Selecting previously unselected package autotools-dev.
Preparing to unpack .../57-autotools-dev_20180224.1+nmu1_all.deb ...
Unpacking autotools-dev (20180224.1+nmu1) ...
Selecting previously unselected package automake.
Preparing to unpack .../58-automake_1%3a1.16.3-2_all.deb ...
Unpacking automake (1:1.16.3-2) ...
Selecting previously unselected package libltdl-dev:amd64.
Preparing to unpack .../59-libltdl-dev_2.4.6-15_amd64.deb ...
Unpacking libltdl-dev:amd64 (2.4.6-15) ...
Selecting previously unselected package libilmbase-dev:amd64.
Preparing to unpack .../60-libilmbase-dev_2.5.4-1_amd64.deb ...
Unpacking libilmbase-dev:amd64 (2.5.4-1) ...
Selecting previously unselected package libopenexr-dev.
Preparing to unpack .../61-libopenexr-dev_2.5.4-2+deb11u1_amd64.deb ...
Unpacking libopenexr-dev (2.5.4-2+deb11u1) ...
Selecting previously unselected package libgirepository-1.0-1:amd64.
Preparing to unpack .../62-libgirepository-1.0-1_1.66.1-1+b1_amd64.deb ...
Unpacking libgirepository-1.0-1:amd64 (1.66.1-1+b1) ...
Selecting previously unselected package gir1.2-glib-2.0:amd64.
Preparing to unpack .../63-gir1.2-glib-2.0_1.66.1-1+b1_amd64.deb ...
Unpacking gir1.2-glib-2.0:amd64 (1.66.1-1+b1) ...
Selecting previously unselected package gir1.2-freedesktop:amd64.
Preparing to unpack .../64-gir1.2-freedesktop_1.66.1-1+b1_amd64.deb ...
Unpacking gir1.2-freedesktop:amd64 (1.66.1-1+b1) ...
Selecting previously unselected package libgdk-pixbuf2.0-common.
Preparing to unpack .../65-libgdk-pixbuf2.0-common_2.42.2+dfsg-1+deb11u1_all.deb ...
Unpacking libgdk-pixbuf2.0-common (2.42.2+dfsg-1+deb11u1) ...
Selecting previously unselected package shared-mime-info.
Preparing to unpack .../66-shared-mime-info_2.0-1_amd64.deb ...
Unpacking shared-mime-info (2.0-1) ...
Selecting previously unselected package libgdk-pixbuf-2.0-0:amd64.
Preparing to unpack .../67-libgdk-pixbuf-2.0-0_2.42.2+dfsg-1+deb11u1_amd64.deb ...
Unpacking libgdk-pixbuf-2.0-0:amd64 (2.42.2+dfsg-1+deb11u1) ...
Selecting previously unselected package gir1.2-gdkpixbuf-2.0:amd64.
Preparing to unpack .../68-gir1.2-gdkpixbuf-2.0_2.42.2+dfsg-1+deb11u1_amd64.deb ...
Unpacking gir1.2-gdkpixbuf-2.0:amd64 (2.42.2+dfsg-1+deb11u1) ...
Selecting previously unselected package libcairo-gobject2:amd64.
Preparing to unpack .../69-libcairo-gobject2_1.16.0-5_amd64.deb ...
Unpacking libcairo-gobject2:amd64 (1.16.0-5) ...
Selecting previously unselected package librsvg2-2:amd64.
Preparing to unpack .../70-librsvg2-2_2.50.3+dfsg-1_amd64.deb ...
Unpacking librsvg2-2:amd64 (2.50.3+dfsg-1) ...
Selecting previously unselected package gir1.2-rsvg-2.0:amd64.
Preparing to unpack .../71-gir1.2-rsvg-2.0_2.50.3+dfsg-1_amd64.deb ...
Unpacking gir1.2-rsvg-2.0:amd64 (2.50.3+dfsg-1) ...
Selecting previously unselected package liblzo2-2:amd64.
Preparing to unpack .../72-liblzo2-2_2.10-2_amd64.deb ...
Unpacking liblzo2-2:amd64 (2.10-2) ...
Selecting previously unselected package libcairo-script-interpreter2:amd64.
Preparing to unpack .../73-libcairo-script-interpreter2_1.16.0-5_amd64.deb ...
Unpacking libcairo-script-interpreter2:amd64 (1.16.0-5) ...
Selecting previously unselected package libexpat1-dev:amd64.
Preparing to unpack .../74-libexpat1-dev_2.2.10-2+deb11u5_amd64.deb ...
Unpacking libexpat1-dev:amd64 (2.2.10-2+deb11u5) ...
Selecting previously unselected package uuid-dev:amd64.
Preparing to unpack .../75-uuid-dev_2.36.1-8+deb11u1_amd64.deb ...
Unpacking uuid-dev:amd64 (2.36.1-8+deb11u1) ...
Selecting previously unselected package libfontconfig-dev:amd64.
Preparing to unpack .../76-libfontconfig-dev_2.13.1-4.2_amd64.deb ...
Unpacking libfontconfig-dev:amd64 (2.13.1-4.2) ...
Selecting previously unselected package libfontconfig1-dev:amd64.
Preparing to unpack .../77-libfontconfig1-dev_2.13.1-4.2_amd64.deb ...
Unpacking libfontconfig1-dev:amd64 (2.13.1-4.2) ...
Selecting previously unselected package libxrender-dev:amd64.
Preparing to unpack .../78-libxrender-dev_1%3a0.9.10-1_amd64.deb ...
Unpacking libxrender-dev:amd64 (1:0.9.10-1) ...
Selecting previously unselected package x11proto-xext-dev.
Preparing to unpack .../79-x11proto-xext-dev_2020.1-1_all.deb ...
Unpacking x11proto-xext-dev (2020.1-1) ...
Selecting previously unselected package libxext-dev:amd64.
Preparing to unpack .../80-libxext-dev_2%3a1.3.3-1.1_amd64.deb ...
Unpacking libxext-dev:amd64 (2:1.3.3-1.1) ...
Selecting previously unselected package x11-common.
Preparing to unpack .../81-x11-common_1%3a7.7+22_all.deb ...
Unpacking x11-common (1:7.7+22) ...
Selecting previously unselected package libice6:amd64.
Preparing to unpack .../82-libice6_2%3a1.0.10-1_amd64.deb ...
Unpacking libice6:amd64 (2:1.0.10-1) ...
Selecting previously unselected package libsm6:amd64.
Preparing to unpack .../83-libsm6_2%3a1.2.3-1_amd64.deb ...
Unpacking libsm6:amd64 (2:1.2.3-1) ...
Selecting previously unselected package libice-dev:amd64.
Preparing to unpack .../84-libice-dev_2%3a1.0.10-1_amd64.deb ...
Unpacking libice-dev:amd64 (2:1.0.10-1) ...
Selecting previously unselected package libsm-dev:amd64.
Preparing to unpack .../85-libsm-dev_2%3a1.2.3-1_amd64.deb ...
Unpacking libsm-dev:amd64 (2:1.2.3-1) ...
Selecting previously unselected package libpixman-1-dev:amd64.
Preparing to unpack .../86-libpixman-1-dev_0.40.0-1.1~deb11u1_amd64.deb ...
Unpacking libpixman-1-dev:amd64 (0.40.0-1.1~deb11u1) ...
Selecting previously unselected package libxcb-render0-dev:amd64.
Preparing to unpack .../87-libxcb-render0-dev_1.14-3_amd64.deb ...
Unpacking libxcb-render0-dev:amd64 (1.14-3) ...
Selecting previously unselected package libxcb-shm0-dev:amd64.
Preparing to unpack .../88-libxcb-shm0-dev_1.14-3_amd64.deb ...
Unpacking libxcb-shm0-dev:amd64 (1.14-3) ...
Selecting previously unselected package libffi-dev:amd64.
Preparing to unpack .../89-libffi-dev_3.3-6_amd64.deb ...
Unpacking libffi-dev:amd64 (3.3-6) ...
Selecting previously unselected package libglib2.0-data.
Preparing to unpack .../90-libglib2.0-data_2.66.8-1_all.deb ...
Unpacking libglib2.0-data (2.66.8-1) ...
Selecting previously unselected package libelf1:amd64.
Preparing to unpack .../91-libelf1_0.183-1_amd64.deb ...
Unpacking libelf1:amd64 (0.183-1) ...
Selecting previously unselected package libglib2.0-bin.
Preparing to unpack .../92-libglib2.0-bin_2.66.8-1_amd64.deb ...
Unpacking libglib2.0-bin (2.66.8-1) ...
Selecting previously unselected package libpython3.9-minimal:amd64.
Preparing to unpack .../93-libpython3.9-minimal_3.9.2-1_amd64.deb ...
Unpacking libpython3.9-minimal:amd64 (3.9.2-1) ...
Selecting previously unselected package python3.9-minimal.
Preparing to unpack .../94-python3.9-minimal_3.9.2-1_amd64.deb ...
Unpacking python3.9-minimal (3.9.2-1) ...
Setting up libpython3.9-minimal:amd64 (3.9.2-1) ...
Setting up python3.9-minimal (3.9.2-1) ...
Traceback (most recent call last):
  File "/usr/lib/python3.9/py_compile.py", line 215, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/py_compile.py", line 207, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.9/py_compile.py", line 172, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 126, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/__pycache__/__future__.cpython-39.pyc.140471864038320'
dpkg: error processing package python3.9-minimal (--configure):
 installed python3.9-minimal package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 python3.9-minimal
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c if [ ${INSTALL_IMAGEMAGICK} = true ]; then     apt-get install -yqq libmagickwand-dev imagemagick &&     if [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then       cd /tmp &&       if [ ${IMAGEMAGICK_VERSION} = "latest" ]; then         git clone https://github.com/Imagick/imagick;       else         git clone --branch ${IMAGEMAGICK_VERSION} https://github.com/Imagick/imagick;       fi &&       cd imagick &&       phpize &&       ./configure &&       make &&       make install &&       rm -r /tmp/imagick;     else       pecl install imagick;     fi &&     docker-php-ext-enable imagick;     php -m | grep -q 'imagick' ;fi' returned a non-zero code: 1
ERROR: Service 'php82-fpm' failed to build : Build failed
```

**Comment by Tannenfels** [comment]
> see #3132

Tried adding `apt-get update`, did not help me.

**Comment by Tannenfels** [comment]
Any update yet?
