### ISSUE TITLE
File missing on docker-compose

### ISSUE THREAD

**Issue by GlenHughes** [laradock/laradock#565]
Hi,

I'm trying to set your container up on my Windows 10 Home machine. I'm using Docker Toolbox. I followed your steps by cloning the repo and then typed "docker-compose up -d nginx mysql redis beanstalkd" into the Powershell and I keep on getting this error:

PS C:\var\docker\laradock> docker-compose up -d nginx mysql redis beanstalkd
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 65, in main
  File "compose\cli\main.py", line 117, in perform_command
  File "compose\cli\main.py", line 849, in up
  File "compose\project.py", line 372, in up
  File "compose\project.py", line 539, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 33, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\client.py", line 139, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1057, in request
  File "httplib.py", line 1097, in _send_request
  File "httplib.py", line 1053, in endheaders
  File "httplib.py", line 897, in _send_output
  File "httplib.py", line 859, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 49, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
docker-compose returned -1

Any ideas how I can get this fixed?

Thank you

**Comment by philtrep** [comment]
@GlenHughes we have a Laradock-Toolbox branch you can try but my suggestion is to not use Docker Toolbox. Docker Native for Windows is what you want to be using.

**Comment by GlenHughes** [comment]
Thanks for getting back to me. I'm currently running Windows 10 Home which isn't supported for Docker Native yet. Maybe I need to try a different container.

**Comment by epineda** [comment]
workaround: reinstall docker toolbox (it works for me)

**Comment by xf789050** [comment]
I was wondering if you started the normal docker daemon

**Comment by xf789050** [comment]
I was wondering if you started the normal docker daemon？
