### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by chisumo2016** [laradock/laradock#886]
C:\Users\bundalla\Desktop\advancelaravel54\laradock> docker-compose up -d nginx mysql
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 117, in perform_command
  File "compose\cli\main.py", line 922, in up
  File "compose\project.py", line 385, in up
  File "compose\project.py", line 603, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 90, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 183, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose

**Comment by bestlong** [comment]
Hi @chisumo2016 Need more infomation:

docker version
docker-compose version

**Comment by mikeerickson** [comment]
@chisumo2016 Please supply the addition information requested by @bestlong 

Unable to assist without more inform.  I will leave this issue open for another week (will be closing 2017.05.19 if no more information supplied).

**Comment by webstractions** [comment]
I get this error when running any docker-compose function with the basic Windows command prompt. If I use the Docker Quickstart Terminal, then there are no errors. 

I am running Docker Toolbox on Windows 7.

**Comment by elickzhao** [comment]
```
 @FOR /f "tokens=*" %i IN ('docker-machine env default') DO @%i
```
