### ISSUE TITLE
"docker-compose up -d workspace" failed.

### ISSUE THREAD

**Issue by sumihiro** [laradock/laradock#949]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Docker-compose version (`$ docker-compose -v`): docker-compose version 1.13.0, build 1719ceb
- Python version (`$ python -V`)Python 2.7.10
- Laradock commit (`$ git rev-parse HEAD`): b2ad5f16e8e82fd5f1f9364ba9b26b85df212c7f
- System info (Mac, PC, Linux): Mac
- System info disto/version: macOS 10.12.4（16E195）

##### What seems to be going wrong?

"docker-compose up -d workspace" failed with "UnicodeDecodeError".

I cleaned up my Docker environment.
Then I tried to install laradock, but it failed.

This is my all log.

```
project sumi$ docker system prune
WARNING! This will remove:
	- all stopped containers
	- all volumes not used by at least one container
	- all networks not used by at least one container
	- all dangling images
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0 B
project sumi$ git clone https://github.com/Laradock/laradock.git
Cloning into 'laradock'...
remote: Counting objects: 4957, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 4957 (delta 2), reused 0 (delta 0), pack-reused 4944
Receiving objects: 100% (4957/4957), 5.36 MiB | 1.82 MiB/s, done.
Resolving deltas: 100% (2560/2560), done.
project sumi$ cd laradock
laradock sumi$ cp env-example .env
laradock sumi$ docker-compose up -d workspace
Creating network "laradock_default" with the default driver
Creating network "laradock_frontend" with driver "bridge"
Creating network "laradock_backend" with driver "bridge"
Creating volume "laradock_phpmyadmin" with local driver
Creating volume "laradock_rethinkdb" with local driver
Creating volume "laradock_mariadb" with local driver
Creating volume "laradock_elasticsearch-data" with local driver
Creating volume "laradock_postgres" with local driver
Creating volume "laradock_aerospike" with local driver
Creating volume "laradock_redis" with local driver
Creating volume "laradock_minio" with local driver
Creating volume "laradock_caddy" with local driver
Creating volume "laradock_adminer" with local driver
Creating volume "laradock_mysql" with local driver
Creating volume "laradock_neo4j" with local driver
Creating volume "laradock_elasticsearch-plugins" with local driver
Creating volume "laradock_memcached" with local driver
Creating volume "laradock_mssql" with local driver
Creating volume "laradock_percona" with local driver
Creating volume "laradock_mongo" with local driver
Building workspace
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 924, in up
  File "compose/project.py", line 400, in up
  File "compose/service.py", line 307, in ensure_image_exists
  File "compose/service.py", line 871, in build
  File "site-packages/docker/api/build.py", line 141, in build
  File "site-packages/docker/utils/build.py", line 12, in tar
  File "site-packages/docker/utils/build.py", line 43, in exclude_paths
  File "posixpath.py", line 73, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 28: ordinal not in range(128)
Failed to execute script docker-compose
laradock sumi$ 
```

_____

##### What should be happening instead?

"docker-compose up -d workspace" will finish successfully.

_____

##### How might we be able to reproduce the error?

It causes anytime.

_____

**Comment by sumihiro** [comment]
I found solution.
My path to laradock contains Unicode chars, like "/User/me/プロジェクト/laradock".
I changed it to "/User/me/Project/laradock", and errors are gone.

I hope that someone will fix this.
